[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "GuessTheSongBot"
version = "0.1.0"
description = "A Discord bot to guess songs from lyrics"
requires-python = ">=3.8"
dependencies = [
    "discord.py>=2.00",
    "requests"
]